# 1. Files excluded from Jekyll builds
exclude:
  - README.md
  - screenshot.png
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - demo/*
  - alembic-jekyll-theme.gemspec

# 2. Installed Gems
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-feed
  - jemoji

# 3. Gem settings
paginate: 4 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
author: Sotra Birøktarlag # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: Sotra Birøktarlag # jekyll-seo-tag > real name
  links: # jekyll-seo-tag > social aliases (sameAs)
    - https://www.facebook.com/groups/419165308221828/

#https://github.com/git-no/jekyll-breadcrumbs
breadcrumbs:
  root:
    hide: false # show breadcrumbs on root/home page
    image: true # Show image or title text

# 4. Jekyll settings
sass:
style: compressed # Style compression
permalink: /:title/ # Permalink pretty style (/YYYY/MM/DD/page-name/), only title permalink: /:title/
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/Oslo # Timezone for blog posts and alike

# 5. Collections
collections:
  posts:
    title: Innlegg # Needed for Siteleaf
    output: true
    # description: "Innlegg fra Sotra Birøktarlag" # The post list page content
    feature_text: |
      Innlegg fra Sotra Birøktarlag
    feature_image: "https://unsplash.it/1300/400?image=1067"

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing
  - scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
      image: "/assets/placeholder-social.png" # Default image for sharing

# 7. Site settings
# encoding: UTF-8 # Make sure the encoding is right, default is utf-8
title: "Sotra Birøktarlag" # Site name or title, also used in jekyll-seo-tag
logo: "/assets/placeholder-logo.svg" # Site logo, also used in jekyll-seo-tag
description: "Nyheter og informasjon fra ditt lokale birøktarlag" # Site description and default description, also used in jekyll-seo-tag
url: "xn--sotrabirktarlag-dub.no" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/SotraBiroktarlag/sotrabirokt/"
email: "sotra.biroektarlag@gmail.com"
lang: nb-no

# 8. Site navigation
navigation_header:
  Hjem: /
  Blogg: /blog/
  Søk: /search/
  Medlemskap: /medlemskap/
  Arrangementer: /arrangementer/
  Bli birøkter: /nybegynner/
  Om: /om/
  Kjøp kuber: /kuber/

social_links:
  Facebook: https://www.facebook.com/groups/419165308221828/
  link: https://www.sotrabirøktarlag.no
